import asyncio
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from app.models.schemas import QuestionConfig
from app.services.question_generator import generate_questions_stream
from app.services.task_manager import task_manager

router = APIRouter(prefix="/api")


@router.post("/generate")
async def generate(config: QuestionConfig):
    if not config.doc_ids:
        raise HTTPException(status_code=400, detail="At least one document must be selected")
    if not config.question_types:
        raise HTTPException(status_code=400, detail="At least one question type must be selected")

    task_id = task_manager.create_task()

    async def _run():
        task_manager.update_task(task_id, status="running", message="Starting generation...")
        try:
            async for event in generate_questions_stream(config):
                if event["event"] == "progress":
                    task = task_manager.get_task(task_id)
                    existing = task["questions"] if task else []
                    existing.extend(event.get("questions", []))
                    task_manager.update_task(
                        task_id,
                        questions=existing,
                        total_so_far=event.get("total_so_far", 0),
                        message=f"Generated {event.get('total_so_far', 0)} questions so far",
                    )
                elif event["event"] == "status":
                    task_manager.update_task(task_id, message=event.get("message", ""))
                elif event["event"] == "warning":
                    ts = task_manager.get_task(task_id)
                    prev = ts.get("message", "") if ts else ""
                    task_manager.update_task(task_id, message=f"{prev} | {event.get('message', '')}")
                elif event["event"] == "done":
                    task_manager.update_task(
                        task_id,
                        status="done",
                        questions=event.get("questions", []),
                        total_so_far=event.get("total", 0),
                        message=f"Completed — {event.get('total', 0)} questions generated",
                    )
                elif event["event"] == "error":
                    task_manager.update_task(
                        task_id,
                        status="error",
                        error=event.get("message", "Unknown error"),
                    )
        except Exception as e:
            task_manager.update_task(task_id, status="error", error=str(e))

    asyncio.create_task(_run())

    return {"task_id": task_id, "status": "queued"}


@router.get("/generate/{task_id}")
async def get_generation_status(task_id: str):
    task = task_manager.get_task(task_id)
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    return task


class PDFRequest(BaseModel):
    questions: list[dict]


@router.post("/generate-pdf")
async def generate_pdf(req: PDFRequest):
    import os
    import re
    from io import BytesIO
    from fpdf import FPDF

    import app as _app_mod
    _APP_DIR = os.path.dirname(os.path.dirname(os.path.abspath(_app_mod.__file__)))

    FONT_NAME = "Helvetica"
    FONT_DIRS = [
        os.path.join(_APP_DIR, "app", "static", "fonts"),
        "/usr/share/fonts/truetype/dejavu/",
        "/usr/share/fonts/dejavu/",
        "/System/Library/Fonts/",
        "/Library/Fonts/",
        "/System/Library/Fonts/Supplemental/",
    ]
    FONT_DIR = None
    for d in FONT_DIRS:
        if os.path.isdir(d):
            FONT_DIR = d
            break

    def safe(t: str) -> str:
        if FONT_NAME == "Helvetica":
            return t.encode("latin-1", errors="replace").decode("latin-1")
        return t

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    if FONT_DIR:
        regular = os.path.join(FONT_DIR, "DejaVuSans.ttf")
        bold = os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf")
        if os.path.exists(regular):
            FONT_NAME = "DejaVu"
            pdf.add_font(FONT_NAME, "", regular)
            if os.path.exists(bold):
                pdf.add_font(FONT_NAME, "B", bold)

    l_margin = 15
    r_margin = 15
    pdf.set_left_margin(l_margin)
    page_w = 210 - l_margin - r_margin

    pdf.add_page()
    pdf.set_font(FONT_NAME, "B", 18)
    pdf.cell(0, 15, safe("Question Paper"), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font(FONT_NAME, "", 9)
    pdf.cell(0, 7, safe("Generated by Question Generator - IAF"), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(3)

    type_order = {"MCQ": 1, "True/False": 2, "FIB": 3, "Very Short": 4, "Short Answer": 5, "Long Answer": 6}
    domain_order = {"Factual": 1, "Comprehension": 2, "Application": 3}

    sorted_qs = sorted(req.questions, key=lambda q: (
        type_order.get(q.get("question_type", ""), 99),
        domain_order.get(q.get("domain", ""), 99)
    ))

    diff_labels = {"easy": "Easy", "medium": "Medium", "hard": "Hard"}

    for i, q in enumerate(sorted_qs, 1):
        qtype = q.get("question_type", "")
        domain = q.get("domain", "Factual")
        difficulty = q.get("difficulty", "medium")
        marks = q.get("marks", 1)
        source = q.get("source", "")
        qtext = q.get("question_text", "")
        opts = q.get("options", []) if q.get("options") else []

        meta_parts = [f"Q{i}", qtype, domain, diff_labels.get(difficulty, "Medium"), f"{marks} mks"]
        if source:
            meta_parts.append(source)

        pdf.set_font(FONT_NAME, "B", 8)
        meta_text = " | ".join(meta_parts)
        pdf.set_fill_color(245, 247, 250)
        pdf.cell(0, 6, safe(" " + meta_text), fill=True, new_x="LMARGIN", new_y="NEXT")

        pdf.set_font(FONT_NAME, "", 11)
        qtext = q.get("question_text", "")
        pdf.multi_cell(0, 6, safe(qtext))
        pdf.ln(1)

        if opts and len(opts) == 4:
            pdf.set_font(FONT_NAME, "", 10)
            for label, opt_text in enumerate(opts):
                pdf.cell(0, 6, safe(f"     {opt_text}"), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

        pdf.set_draw_color(210, 215, 222)
        pdf.line(l_margin, pdf.get_y(), 210 - r_margin, pdf.get_y())
        pdf.ln(4)

    pdf.add_page()
    pdf.set_font(FONT_NAME, "B", 16)
    pdf.cell(0, 15, safe("Answer Key"), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_draw_color(30, 77, 140)
    pdf.set_line_width(0.4)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(6)

    for i, q in enumerate(sorted_qs, 1):
        answer = q.get("answer", "")
        pdf.set_font(FONT_NAME, "B", 10)
        pdf.cell(12, 7, safe(f"Q{i}:"), new_x="RIGHT", new_y="TOP")
        pdf.set_font(FONT_NAME, "", 10)
        pdf.multi_cell(0, 7, safe(f"{answer}"))
        pdf.ln(1)

    buf = BytesIO()
    pdf.output(buf)
    buf.seek(0)

    return Response(
        content=buf.read(),
        media_type="application/pdf",
        headers={"Content-Disposition": 'attachment; filename="questions.pdf"'},
    )
